<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />

    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kanini.Ecommerce.Api\Kanini.Ecommerce.Api.csproj" />
    <ProjectReference Include="..\Kanini.Ecommerce.Application\Kanini.Ecommerce.Application.csproj" />
    <ProjectReference Include="..\Kanini.Ecommerce.Domain\Kanini.Ecommerce.Domain.csproj" />
    <ProjectReference Include="..\Kanini.Ecommerce.Data\Kanini.Ecommerce.Data.csproj" />
    <ProjectReference Include="..\Kanini.Ecommerce.Common\Kanini.Ecommerce.Common.csproj" />
  </ItemGroup>

</Project>
