// <auto-generated />
using System;
using Kanini.Ecommerce.Data.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kanini.Ecommerce.Data.Migrations
{
    [DbContext(typeof(EcommerceDatabaseContext))]
    [Migration("20251105063643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("INT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.ToTable("Cart", t =>
                        {
                            t.HasComment("Shopping cart items for customers");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex(new[] { "Name" }, "IX_Categories_Name")
                        .IsUnique();

                    b.ToTable("Categories", t =>
                        {
                            t.HasComment("Product categories with hierarchical support");
                        });

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electronic devices and gadgets",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electronics",
                            TenantId = "admin"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mobile phones and accessories",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Smartphones",
                            ParentCategoryId = 1,
                            TenantId = "admin"
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasComment("Customer's date of birth");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasComment("Customer's first name");

                    b.Property<int?>("Gender")
                        .HasColumnType("INT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasComment("Customer's last name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasComment("Customer's middle name");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers", t =>
                        {
                            t.HasComment("Customer profile information");
                        });

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "456 Oak St, Chennai",
                            City = "Chennai",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            Gender = 2,
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Smith",
                            PinCode = "600002",
                            State = "Tamil Nadu",
                            TenantId = "vendor1",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("DATETIME2");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<decimal?>("ShippingAmount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("ShippingPhone")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR(15)");

                    b.Property<string>("ShippingPinCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("ShippingState")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.HasIndex(new[] { "OrderNumber" }, "IX_Orders_OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("Customer orders and order management");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("INT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasComment("Individual items within an order");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INT");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PaymentDate");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex(new[] { "TransactionId" }, "IX_Payments_TransactionId")
                        .HasDatabaseName("IX_Payments_TransactionId1");

                    b.ToTable("Payments", t =>
                        {
                            t.HasComment("Payment processing and transaction details");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<int?>("MinStockLevel")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("VendorId");

                    b.HasIndex("TenantId", "VendorId");

                    b.HasIndex(new[] { "SKU" }, "IX_Products_SKU")
                        .IsUnique();

                    b.ToTable("Products", t =>
                        {
                            t.HasComment("Product catalog and inventory management");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("BIT");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.HasKey("ImageId");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "IsPrimary");

                    b.ToTable("ProductImages", t =>
                        {
                            t.HasComment("Product images for marketing and display");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.HasIndex(new[] { "Token" }, "IX_RefreshTokens_Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens", t =>
                        {
                            t.HasComment("Refresh tokens for JWT authentication");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("BIT");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("INT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.HasKey("ReviewId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Rating");

                    b.HasIndex("TenantId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.HasIndex(new[] { "TenantId" }, "IX_Reviews_TenantId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasComment("Customer product reviews with tenant isolation");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Shipping", b =>
                {
                    b.Property<int>("ShippingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingId"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("CourierService")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeliveryNotes")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.HasKey("ShippingId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ShippedDate");

                    b.HasIndex("Status");

                    b.HasIndex("TrackingNumber")
                        .IsUnique()
                        .HasFilter("[TrackingNumber] IS NOT NULL");

                    b.ToTable("Shipping", t =>
                        {
                            t.HasComment("Order shipping and delivery tracking");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DATE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATE");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PlanId");

                    b.HasIndex("VendorId");

                    b.HasIndex("VendorId", "IsActive");

                    b.ToTable("Subscriptions", t =>
                        {
                            t.HasComment("Vendor subscription instances");
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INT")
                        .HasComment("Duration in days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<int>("MaxProducts")
                        .HasColumnType("INT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.HasKey("PlanId");

                    b.HasIndex("IsActive");

                    b.HasIndex("PlanName")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans", t =>
                        {
                            t.HasComment("Master subscription plans managed by admin");
                        });

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basic plan with 10 products",
                            DurationDays = 30,
                            IsActive = true,
                            IsDeleted = false,
                            MaxProducts = 10,
                            PlanName = "Basic",
                            Price = 999m,
                            TenantId = "admin"
                        },
                        new
                        {
                            PlanId = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Standard plan with 50 products",
                            DurationDays = 30,
                            IsActive = true,
                            IsDeleted = false,
                            MaxProducts = 50,
                            PlanName = "Standard",
                            Price = 2999m,
                            TenantId = "admin"
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int")
                        .HasComment("Number of failed login attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("BIT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasComment("Last successful login timestamp");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2")
                        .HasComment("Account lockout until this time");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<int>("Role")
                        .HasColumnType("INT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "IX_Users_Phone")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@ecommerce.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword123",
                            Phone = "9876543210",
                            Role = 3,
                            TenantId = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer1@gmail.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword123",
                            Phone = "9876543211",
                            Role = 1,
                            TenantId = "vendor1"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vendor1@gmail.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailVerified = true,
                            PasswordHash = "hashedpassword123",
                            Phone = "9876543212",
                            Role = 2,
                            TenantId = "vendor1"
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"));

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("BusinessLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("CurrentPlan")
                        .HasColumnType("INT")
                        .HasComment("Current subscription plan of the vendor");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)")
                        .HasComment("Registration document file path");

                    b.Property<int>("DocumentStatus")
                        .HasColumnType("INT")
                        .HasComment("Document verification status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)")
                        .HasComment("Reason for document rejection");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasDefaultValueSql("NEWID()")
                        .HasComment("Tenant isolation - each vendor has unique tenant ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Admin who verified the document");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("DATETIME2")
                        .HasComment("Document verification timestamp");

                    b.HasKey("VendorId");

                    b.HasIndex("BusinessLicenseNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "BusinessLicenseNumber" }, "IX_Vendors_BusinessLicense")
                        .IsUnique();

                    b.ToTable("Vendors", t =>
                        {
                            t.HasComment("Vendor information and business details");
                        });

                    b.HasData(
                        new
                        {
                            VendorId = 1,
                            BusinessAddress = "123 Main St, Chennai",
                            BusinessLicenseNumber = "BL123456",
                            BusinessName = "Tech Store",
                            City = "Chennai",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentPlan = 1,
                            DocumentPath = "/docs/license.pdf",
                            DocumentStatus = 2,
                            IsActive = true,
                            IsDeleted = false,
                            OwnerName = "John Doe",
                            PinCode = "600001",
                            State = "Tamil Nadu",
                            Status = 1,
                            TenantId = "vendor1",
                            UserId = 3,
                            VerifiedBy = "Admin",
                            VerifiedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Cart", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Customer", "Customer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Category", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("Kanini.Ecommerce.Domain.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Order", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Orders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Kanini.Ecommerce.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Products")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Review", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Shipping", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Order", "Order")
                        .WithOne("Shipping")
                        .HasForeignKey("Kanini.Ecommerce.Domain.Entities.Shipping", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kanini.Ecommerce.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Subscriptions")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Vendor", b =>
                {
                    b.HasOne("Kanini.Ecommerce.Domain.Entities.User", "User")
                        .WithOne("Vendor")
                        .HasForeignKey("Kanini.Ecommerce.Domain.Entities.Vendor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");

                    b.Navigation("Shipping");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Images");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Kanini.Ecommerce.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
